// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy4xcVHnvK_-UUv8NxjyqLQBNOJmwewTo',
    appId: '1:435890288277:web:64ad7d2d09bb615c5b8d9c',
    messagingSenderId: '435890288277',
    projectId: 'gacha-scheduler',
    authDomain: 'gacha-scheduler.firebaseapp.com',
    storageBucket: 'gacha-scheduler.firebasestorage.app',
    measurementId: 'G-VECLVJB5ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARubwPgzL-kNnDVRsAmJ2mhV1QzilrDgk',
    appId: '1:435890288277:android:0e34e0bcef15474d5b8d9c',
    messagingSenderId: '435890288277',
    projectId: 'gacha-scheduler',
    storageBucket: 'gacha-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6YUhcq0W1fJYnEK5WSCWNdA5-AXALnsI',
    appId: '1:435890288277:ios:c8bd6186037cd1c55b8d9c',
    messagingSenderId: '435890288277',
    projectId: 'gacha-scheduler',
    storageBucket: 'gacha-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.frontendMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6YUhcq0W1fJYnEK5WSCWNdA5-AXALnsI',
    appId: '1:435890288277:ios:c8bd6186037cd1c55b8d9c',
    messagingSenderId: '435890288277',
    projectId: 'gacha-scheduler',
    storageBucket: 'gacha-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.frontendMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy4xcVHnvK_-UUv8NxjyqLQBNOJmwewTo',
    appId: '1:435890288277:web:d82bec65d16bccdc5b8d9c',
    messagingSenderId: '435890288277',
    projectId: 'gacha-scheduler',
    authDomain: 'gacha-scheduler.firebaseapp.com',
    storageBucket: 'gacha-scheduler.firebasestorage.app',
    measurementId: 'G-PZ7RKWY8KV',
  );
}
